name: ci_test

on:

  workflow_dispatch:
    inputs:
      ref_sha:
        description: 'SHA of ref'
        required: false
      update_cache:
        description: 'update cache'
        required: false        

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CUDA_VERSION: 11.2.2
  cuda_version_major_minor: 11.2

jobs:


  windows:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-2019
    
    steps:

      - name: checkout head
        if: ${{ ! github.event.inputs.ref_sha}}
        uses: actions/checkout@v2

      - name: vcpkg
        run: |
          vcpkg install --triplet x64-windows "@.vcpkg_deps.txt"

      - name: Save Cache VCPKG
        id: cache_save_vcpkg
        uses: actions/cache@v2
        continue-on-error: true
        if: ${{ github.event.inputs.update_cache}}
        env:
          cache-name: cache-vcpkg
        with:
          path: |
            C:/vcpkg
            !C:/vcpkg/buildtrees
          key: ${{ runner.os }}−${{ env.cache-name }}-${{github.sha}}-${{ github.event.inputs.ref_sha}}